#ifndef REFERENCE_MONITOR_H
#define REFERENCE_MONITOR_H

#define MODNAME "REFERENCE_MONITOR"

#define REFMON_STATE_OFF 0b00
#define REFMON_STATE_ON 0b01
#define REFMON_STATE_REC_OFF 0b10
#define REFMON_STATE_REC_ON 0b11

#endif // !REFERENCE_MONITOR_H
